language: node_js
node_js:
- "10"

sudo: required

before_install: 
  - sudo apt-get install libgconf-2-4
  - npm install tslint

testSmokeCy: &testSmokeCy
  script:
  - npm run cy:run:smoke -- --record --key $CY_KEY --parallel --group tests
  - kill $(jobs -p) || true

jobs:
  fast_finish: true
  allow_failures:
  include:
  - script:
    name: "Cypress Node 1"
    <<: *testSmokeCy
  - script:
    name: "Cypress Node 2"
    <<: *testSmokeCy

notifications: 
  email:
    recipients:
      - gb8may@gmail.com
      
    on_success: never
    on_failure: never
