language: bash
sudo: required
services:
  - docker

testSmokeCy: &testSmokeCy
  install:
  - docker run --rm -it -v $PWD:/e2e -w /e2e -e CYPRESS_RECORD_KEY=$CY_KEY cypress/included:3.4.0 --record --parallel --group docker --ci-build-id TRAVIS_BUILD_ID
  - kill $(jobs -p) || true

jobs:
  fast_finish: true
  allow_failures:
  include:
  - script:
    name: "Cypress Container 1"
    <<: *testSmokeCy
  - script:
    name: "Cypress Container 2"
    <<: *testSmokeCy  

notifications: 
  email:
    recipients:
      - gb8may@gmail.com
      
    on_success: always
    on_failure: always

cache:
  apt: true
  docker: true
  directories:
  - ~/.docker
  - ~/.cache
