languade: ruby

sudo: required

services:
  - docker

before_install: 
  - sudo apt-get install libgconf-2-4
  - npm install tslint

testSmokeCy: &testSmokeCy
script:
  - docker run --rm -it -v $PWD:/e2e -w /e2e cypress/included:3.4.0
  - kill $(jobs -p) || true

jobs:
  fast_finish: true
  allow_failures:
  include:
  - script:
    name: "Cypress Container 1"
    <<: *testSmokeCy
  - script:
    name: "Cypress Container 2"
    <<: *testSmokeCy

notifications: 
  email:
    recipients:
      - gb8may@gmail.com
      
    on_success: never
    on_failure: never
