language: node_js
node_js:
- "10"

sudo: required

install:
  - npm run cy:run:smoke -- --record --key $CY_KEY
  - kill $(jobs -p) || true

notifications: 
  email:
    recipients:
      - gb8may@gmail.com
      
    on_success: never
    on_failure: never
